backend:
  name: git-gateway
  branch: youuBlog2
media_folder: public/assets
public_folder: /assets
local_backend: true
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    fields:
      - { label: "Title", name: "title", widget: "string" , hint: "you can write instruction here"}
      - { label: "Description", name: "description", widget: "text" , hint: "you can write instruction here"}
      # - { label: "Author", name: "author", widget: "string" }
      - { label: 'Date', name: 'date', widget: 'datetime', default: '', date_format: 'dddd MMMM Do', time_format: 'ha', format: 'YYYY-MM-DDTHH:mm:ssZ', picker_utc: false, hint: "you can write instruction here"}
      - { label: "Tags", name: "tags", widget: "list", default: ["Post","Featured"],hint: "you can write instruction here" }
      - { label: "Post Tags", 
          name: "postTags", 
          widget: "list", 
          max: 4, 
          min: 1, 
          default: ["Exclusive","Mental Health","Addicition","Drugs"] ,
          hint: "you can write instruction here"
        }
      - { label: "Featured Image", name: "image", widget: "image" , required: false, hint: "you can write instruction here"}
      - { label: "Image Caption", name: "imageAlt", widget: "string" }
      - { label: "Video URL", name: "videoURL", widget: "string" ,hint: "you can only use embed url for videos."}
      - { label: "Body", name: "body", widget: "markdown", hint: "you can write instruction here"}

      # - { label: "Category",
      #     name: "category",
      #     widget: "select",
      #     multiple: true,
      #     min: 1,
      #     max: 3,
      #     options: ["Design", "UX", "Dev"],
      #     default: ["Design"]
      #   }
      # - { 
      #   label: "Gallery",
      #   name: "galleryImages",
      #   widget: "list",
      #   summary: '{{fields.image}}',
      #   field: {label: Image, name: image, widget: image}
      #   }
      # - label: "Testimonials"
      #   name: "testimonials"
      #   widget: "list"
      #   summary: '{{fields.quote}} - {{fields.author.name}}'
      #   fields:
      #     - {label: Quote, name: quote, widget: string, default: "Everything is awesome!"}
      #     - label: Author
      #       name: author
      #       widget: object
      #       fields:
      #         - {label: Name, name: name, widget: string, default: "Emmet"}
      #         - {label: Avatar, name: avatar, widget: image, default: "/assets/blog.svg"}
  - name: "feature"
    label: "Feature"
    folder: "src/features"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Label", name: "label", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["feature"] }
      - { label: "Description", name: "description", widget: "string" }
      - { label: 'Date', name: 'date', widget: 'datetime', default: '', date_format: 'dddd MMMM Do', time_format: 'ha', format: 'YYYY-MM-DDTHH:mm:ssZ', picker_utc: false }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "slider"
    label: "Slider"
    folder: "src/slider"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    fields:
      - { label: "Button Text", name: "slideButtonText", widget: "string" }
      - { label: "Short Title", name: "slideShortTitle", widget: "string" }
      - { label: "Slide Title", name: "slideTitle", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["slider"] }
      - { label: "Pointer", name: "sliderPointer", widget: "list" }
      - { label: "Description", name: "sliderDescription", widget: "text"}
      - { label: 'Date', name: 'date', widget: 'datetime', default: '', date_format: 'dddd MMMM Do', time_format: 'ha', format: 'YYYY-MM-DDTHH:mm:ssZ', picker_utc: false }
      - { label: "Video URL", name: "videoURL", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "contact"
    label: "Contact"
    folder: "src/contact"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    fields:
      - { label: "Contact Number",
          name: "contact", 
          widget: "string",
          }
 
   

    